### ISSUE TITLE
Предложение по описаниям

### ISSUE THREAD

**Issue by yaizida** [SQL-Academy/ru.sql-academy#17]
Сразу хочу поблагодарить за крутой проект,  всем советую кто интересуется SQL) 
Но может быть в описании Реляционных и не сделать более понятное описание ? А то тавтология немного выходит. 

"Реляционными называются базы данных, в основе построения которых лежит реляционная модель." 
Определение правильное не спорю, но ... 
Для человека который только начинает вникать не совсем понятна такая формулировка. 
Возможно лучше дополнить
"Реляционными называются базы данных, в основе построения которых лежит реляционная модель.
 В такой базе данные структурированы в виде таблиц, которые содержат строки и столбцы."

**Comment by nvladanov** [comment]
Да, хорошие предложение! обязательно дополним
