### ISSUE TITLE
Неточная проверка решения задания 35

### ISSUE THREAD

**Issue by triadema** [SQL-Academy/ru.sql-academy#18]
Задание требует посчет РАЗЛИЧНЫХ кабинетов, однако при проверке верны решения как с count(*),  которое подсчитывает ВСЕ строки без различия кабинетов (т.е. с "двойниками")
select count(*) as count
from Schedule
WHERE DATE(date) = '2019-09-02'

так и с  distinct classroom, которое даст РАЗЛИЧНЫЕ кабинеты
select count(distinct classroom) as count
from Schedule
WHERE DATE(date) = '2019-09-02'

Просто совпало, что в базе на заданное число не дубликатов кабинетов

**Comment by NepeinAV** [comment]
Спасибо, поправим
