### ISSUE TITLE
Неточность проверки решения в задании 61

### ISSUE THREAD

**Issue by triadema** [SQL-Academy/ru.sql-academy#19]
Проверка показывает правильность решения 2х вариантов решения:
1. Когда указывается промежуток только доя начальной даты
```sql
FROM Rooms
JOIN Reservations ON Rooms.id=Reservations.room_id
WHERE 
(DATE(start_date) BETWEEN '2020-03-16T00:00:00.000Z'
 AND '2020-03-22T00:00:00.000Z')
 AND
 DATEDIFF(end_date, start_date)>=1
 GROUP BY room_id
```
2. Когда указывается этот  промежуток и для начальной и для конечной даты.
2е решение неверно, т. к. конечная дата по сути условия задания может выходить за 12ю неделю.
Добавьте, пожалуйста, в базу данных запись, где начальная дата входит в заданный промежуток, а конечная находится за его пределами и, соответственно исправьте проверку решения.

**Comment by NepeinAV** [comment]
Возможно имеется ввиду какой-то другой промежуток (или условие)?

![image](https://github.com/SQL-Academy/ru.sql-academy/assets/33036510/99006dc0-62a2-4403-8d18-589034e4bf24)
