### ISSUE TITLE
О задании 62

### ISSUE THREAD

**Issue by triadema** [SQL-Academy/ru.sql-academy#20]
В тренажере есть задание 62 по регулярным выражениям, но теории нет. Добавьте, пожалуйста, в курс обзорно о регулярках с примерами выборки части email.

**Comment by NepeinAV** [comment]
В 62 задании не предполагается использование регулярок, для решения достаточно использовать функции SUBSTRING и LOCATE. Но в целом новая тема в курсе про регулярки имеет место быть. Спасибо
