### ISSUE TITLE
Ошибка теста module-2 / 1. Сортировка по убыванию

### ISSUE THREAD

**Issue by Andymnm** [SQL-Academy/ru.sql-academy#22]
course/module-2/sorting

Нет ли ошибки в тесте 1?
Задание:
```
Для каждого отдельного платежа выведите идентификатор товара и сумму, потраченную на него, в отсортированном по убыванию этой суммы виде. Список платежей находится в таблице Payments.
Для вывода суммы используйте псевдоним sum.
```

Решение:
```
SELECT good,
	unit_price sum
FROM Payments
ORDER BY unit_price DESC
```

**Comment by NepeinAV** [comment]
Здравствуйте! Для вопросов по заданиям у нас есть специальный чат в ТГ: https://t.me/sqlacademyorg. Там обычно отвечают очень быстро⚡

В данном задании просят вывести идентификатор товара и "сумму, потраченную на него". В таблице Payments лежит два поля: unit_price и amount, где unit_price - **цена** товара, а amount - количество этого товара в платеже, соответственно, сумма - unit_price * amount

**Comment by SolomonenkoKate** [comment]
Вот верный ответ:

SELECT amount * unit_price AS 'sum',
	good_id AS good
FROM Payments
	JOIN Goods ON Payments.good = Goods.good_id
ORDER BY amount * unit_price DESC
