### ISSUE TITLE
Некорректное условие в 11 задании тренажера

### ISSUE THREAD

**Issue by Dembovich** [SQL-Academy/ru.sql-academy#5]
Условие: "Выведите **пассажиров** с самым длинным ФИО. Пробелы, дефисы и точки считаются частью имени."
А для решения хватает вывода самого длинного ФИО **единственного** пассажира
Понимаю, что может быть несколько пассажиров, но в данной БД он один. Задание возможно решить сортировкой по длине и лимитом. Не кажется заданием средней сложности в таком случаи. Возможно стоит добавить еще одного пассажира с такой длинной ФИО?

**Comment by nvladanov** [comment]
Действительно, добавление еще одного пассажира с такой же длинной ФИО сделает задачу гораздо лучше.
