### ISSUE TITLE
Тренажёр. Задание 24.

### ISSUE THREAD

**Issue by Acinit1** [SQL-Academy/ru.sql-academy#6]
Задание можно решить следующим образом 
```
select member_name,
	unit_price * amount as costs
from Payments
	join FamilyMembers ON FamilyMembers.member_id = Payments.family_member
where Payments.date BETWEEN DATE('2005-06-01') and DATE('2005-07-01')
```
Если добавить еще одну запись в `Payments`, с полем `member_name` с параметром, например, `Flavia Quincey`, то без использования `sum` данное решение не подходит. А задание словно предполагает, что каждый член семьи может покупать несколько раз одну и ту же позицию в разные дни. Может стоит добавить дополнительную запись в `Payments`?

**Comment by Acinit1** [comment]
Хотя можно просто поменять условие задачи, например c `Определить кто и сколько потратил в июне 2005` на `Определить кто и сколько потратил в промежутке с марта по июнь 2005`

**Comment by nvladanov** [comment]
Действительно, стоит добавить еще одну запись в `Payments`.
